config/routes.rb
Rails.application.routes.draw do
  

  
  get 'meetings/new'
  get 'meetings/list_meetings'
  post 'meetings/create'
  get 'meetings/show/:meeting_id' => 'meetings#show', as: 'meeting_show'

  get 'users/list_user'
  get 'users/new_user'

  post 'users/create'

  patch 'users/update_user/:user_id' => 'users#update_user', as: 'update_user'

  get 'users/get_user/:user_id' => 'users#get_user', as: 'get_user'

  delete 'users/delete_user/:user_id' => 'users#delete_user', as: 'user_delete'

  root 'home#index'
  get 'joinmeeting/:meeting_id' => 'home#joinmeeting', as: 'joinmeeting'
  devise_for :users, :controllers =>{ registrations: 'registrations',  :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meetings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def joinmeeting
  	@password = params[:pwd]
  	@meeting_id = params[:meeting_id]
  	@root_url = root_url
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :set_meeting, :only => :show
  def new
  end


  def show
    @meeting_id = params[:meeting_id]
    @root_url = root_url
    @role = current_user.id == @meeting.user_id ? 1 : 0
    @password = @meeting.password
    @userName =  @meeting.user.first_name + " " + @meeting.user.last_name
  end

  def create
  	@zoom_meeting = MeetingCreateService.new(meeting_params,session[:access_token]).create_meeting
    @meeting = Meeting.new
    @meeting.topic = meeting_params[:topic]
    @meeting.meeting_type = meeting_params[:type]
    @meeting.start_time = meeting_params[:start_time]
    @meeting.duration = meeting_params[:duration]
    @meeting.password = meeting_params[:password]
    @meeting.user_id = current_user.id
    @meeting.zoom_meeting_id =  @zoom_meeting["id"]
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to users_list_user_path, notice: 'Meeting was successfully Created.' }
      end
    end
  end

  def list_meetings
  	@meetings = MeetingService.new.list_meetings session[:access_token],current_user.zoom_user_id
    @root_url = root_url
  end

  private
    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:topic, :type, :start_time, :duration, :password, :user_id)
    end

    def set_meeting
      @meeting = Meeting.find_by(zoom_meeting_id: params["meeting_id"])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	
	private
	
	def sign_up_params
		params.require(:user).permit(:name, :first_name, :last_name, :type, :zoom_user_id, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:name, :first_name, :last_name, :type, :zoom_user_id, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	
	after_filter :after_login, :only => :create

	def after_login
		payload = { aud: nil, iss: 'rEbaFtdIQieenQbk3xOPKA', exp: (DateTime.now + 1.day).strftime('%s').to_i, iat: DateTime.now.strftime('%s').to_i}
		secret = "WatHemxRgmUbsbN61I3riWDEN8Ev3NfHEUYk"
		token = JWT.encode payload, secret, 'HS256'
		session[:access_token] = "Bearer "+token
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new_user
  end

  def list_user
    @users_data = UserService.new.all_users session[:access_token]
  end

  def create
    @user = UserCreateService.new(user_params,session[:access_token]).create_user
    @user_local = User.new
    @user_local.email = @user["email"]
    @user_local.first_name = @user["first_name"]
    @user_local.last_name = @user["last_name"]
    @user_local.user_type = @user["type"]
    @user_local.zoom_user_id = @user["id"]
    @user_local.password = "password"
    byebug
    respond_to do |format|
      if @user_local.save
        format.html { redirect_to users_list_user_path, notice: 'User was successfully Created.' }
      end
    end
  end

  def update_user
  end

  def get_user
  end

  def delete_user 
    UserService.new.delete_user params["user_id"],session[:access_token]
  end

  private
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
	def get_pwd url
		url.split('?')[1].present? ? "?"+url.split('?')[1] : " "
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/joinmeeting.html.erb
<button type="submit" class="btn btn-primary" id="join_meeting">Join</button>
<!-- import ZoomMtg dependencies -->
    <script src="https://source.zoom.us/1.8.3/lib/vendor/react.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/react-dom.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/redux.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/redux-thunk.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/jquery.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/lodash.min.js"></script>

    <!-- import ZoomMtg -->
    <script src="https://source.zoom.us/zoom-meeting-1.8.3.min.js"></script>
<script>

	ZoomMtg.preLoadWasm(); // pre download wasm file to save time.
	ZoomMtg.prepareJssdk();

	const API_KEY = "rEbaFtdIQieenQbk3xOPKA"; //"YOUR_API_KEY"
	const API_SECRET = "WatHemxRgmUbsbN61I3riWDEN8Ev3NfHEUYk"; //"YOUR_API_SECRET"
	const url = "https://zoom-api-signature.herokuapp.com"; // YOUR_FETCH_URL_FOR_GET_SIGNATURE

	/** request body to get signature */
	const requestBody = {
	    apiKey: API_KEY,
	    apiSecret: API_SECRET,
	    meetingNumber:  "<%= @meeting_id %>", // "YOUR_HOST_MEETING_NUMBER"
	    role: 0, // 1 for host; 0 for attendee,
	};

	/** meetconfig to join meeting */
	const meetConfig = {
	    meetingNumber:  "<%= @meeting_id %>", // "YOUR_HOST_MEETING_NUMBER"
	    userName: 'Gust User',
	    passWord: '<%= @password %>',
	};
	document
    .getElementById("join_meeting")
    .addEventListener("click", function (e) {
        e.preventDefault();
        /**join meeting called when join button clicked */
        console.log('on Click');
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(requestBody)
        })
            .then(res => res.json())
            .then(data => {
                console.log('signature recieved', data);
                ZoomMtg.init({
                    isSupportAV: true,
                    leaveUrl: '<%= @root_url %>',
                    success: function () {
                        console.log('zoom init success');
                        ZoomMtg.join({
                            meetingNumber: meetConfig.meetingNumber,
                            userName: meetConfig.userName,
                            passWord: meetConfig.passWord,
                            signature: data.signature,
                            apiKey: API_KEY,
                            success: function (success) {
                                console.log('meeting joined success.');
                            },
                            error: function (error) {
                                console.log('you have error in meeting join method',error);
                            }
                        })
                    },
                    error: function (error) {
                        console.log('Error in zoom  meeting init.',error)
                    }
                });
            });
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZoomDemo</title>
    <%= csrf_meta_tags %>
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/1.8.3/css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/1.8.3/css/react-select.css" />

     
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        #zmmtg-root{
            position: unset !important;
        }
    </style>
  </head>

  <body>
  	<% if flash[:notice] %>
	  	<div class="notification is-primary global-notification">
	  		<p class="notice"><%= notice %></p>  		
	  	</div>
  	<% end %>

  	<% if flash[:alert] %>
	  	<div class="notification is-danger global-notification">
	  		<p class="alert"><%= alert %></p>  		
	  	</div>
  	<% end %>
  	<nav class=" navbar is-info">
  		<div class="navbar-brand">
	  		<%= link_to root_path, class: "navbar-item" do %>
	  			<h1 class="title is-5">ZoomDemo</h1>
	  		<% end %>
	  		<div class="navbar-burger burger" data-taget="navbarExample">
	  			<span></span>
	  			<span></span>
	  			<span></span>
	  		</div>
	  	</div>

	  	<div id="navbarExample" class="navbar-menu">
	  		<div class="navbar-end">
	  			<div class="field is-grouped">
	  				<p class="control">
	  					<% if user_signed_in? %>
	  						<%= link_to 'Register User', users_new_user_path, class: "button is-info" %>
	  						<%= link_to 'List User', users_list_user_path, class: "button is-info" %>
							<%= link_to 'Add Meeting', meetings_new_path, class: "button is-info" %>							
							<%= link_to 'List Meeting', meetings_list_meetings_path, class: "button is-info" %>
	  						<%= link_to(current_user.email, edit_registration_path(current_user), class: "button is-info") %>  
	  					<% end %>
	  				</p>
	  				<p class="control">
	  					<%#= link_to "New Tweet", root_path, class: "button is-info is-inverted" %>
	  					<% if user_signed_in? %>
						  
						  <%= link_to('Logout', destroy_user_session_path, class: "button is-info",method: :delete) %>        
						  
						<% else %>

							<%= link_to('Login', new_user_session_path, class: "button is-info") %>  
						  
						<% end %>
	  				</p>
	  			</div>
	  		</div>
	  	</div>
  	</nav>
  	<%= yield %>
  </body>
</html>

app/views/meetings/list_meetings.html.erb
<div class="column is-half ">  
  <% @meetings["meetings"].each do |meeting| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= meeting["topic"] %> </strong><small><%= meeting["start_time"] %></small>
            <p>Duration <%= meeting["duration"]%>  Minutes</p>
            <p>Meeting Id - <%= meeting["id"]%></p>
            <p>Join Url - <%= @root_url + "joinmeeting/"+meeting["id"].to_s + get_pwd(meeting["join_url"]) %></p>
          </div>
        </div>
        
          <nav class="level">
            <div class="level-left is-mobile">
                <%= link_to "Start", meeting_show_path(meeting["id"]), class: "level-item" %>
                <%#= link_to edit_room_path(room), class: "level-item" do %>
                  <!-- <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span> -->
                <%# end %>
                <%#= link_to user_delete_path(meeting["id"]), method: :delete, data: { confirm: 'Are you sure want to delete Room?' } do%>
                  <!-- <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span> -->
                <%# end %>
              
            </div>
          </nav>
        
      </article>
    </div>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="column is-half ">
  <article class="media box">
    <div class="media-content">
    	<%= form_for :meeting, url: "create" do |form| %>
		  
        <div class="field">
          <%= form.label :topic, class: "label" %>
          <div class="control">            
            <%= form.text_field :topic, class: "input", placeholder: "Enter topic" %><br>            
          </div>
        </div>
        <%= form.hidden_field :user_id, class: "input", placeholder: "Enter Zoom user_id", value: current_user.zoom_user_id %><br>
        

        <div class="field">
          <%= form.label :type, class: "label" %>
          <div class="control">
            <div class="select">
              <select id="meeting_type" name="meeting[type]" placeholder="Select User Type">
                <option value="2">Scheduled meeting</option>
                <option value="1">Instant meeting</option>
              </select>
            </div>
          </div>
        </div>


        <div class="field">
          <%= form.label :start_time, class: "label" %>
          <div class="control">            
            <%= form.text_field :start_time, class: "input", placeholder: "Select Sart time" %><br>            
          </div>
        </div>

        <div class="field">
          <%= form.label :duration, class: "label" %>
          <div class="control">            
            <%= form.number_field :duration, class: "input", placeholder: "Enter Duration in Min" %><br>            
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>
          <div class="control">            
            <%= form.text_field :password, class: "input", placeholder: "Enter password" %><br>            
          </div>
        </div>

        
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit class: "button is-link" %>
          </div>
          <div class="control">
            <%#= link_to "Cancel", rooms_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
</div>

app/views/meetings/show.html.erb
<button type="submit" class="btn btn-primary" id="join_meeting">Join</button>
<div class="modal" id="ga_chat_modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Modal title</p>
      <button id= "ga_chat_close_button" class="delete" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <!-- Content ... -->
    </section>
    <footer class="modal-card-foot">
      <input class="input" placeholder="enter massage..." type="text"  id="user_massage">
      <button class="button is-success">Send</button>
      <!-- <button class="button">Cancel</button> -->
    </footer>
  </div>
</div>
<!-- import ZoomMtg dependencies -->
    <script src="https://source.zoom.us/1.8.3/lib/vendor/react.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/react-dom.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/redux.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/redux-thunk.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/jquery.min.js"></script>
    <script src="https://source.zoom.us/1.8.3/lib/vendor/lodash.min.js"></script>

    <!-- import ZoomMtg -->
    <script src="https://source.zoom.us/zoom-meeting-1.8.3.min.js"></script>
<script>

	ZoomMtg.preLoadWasm(); // pre download wasm file to save time.
	ZoomMtg.prepareJssdk();

	const API_KEY = "rEbaFtdIQieenQbk3xOPKA"; //"YOUR_API_KEY"
	const API_SECRET = "WatHemxRgmUbsbN61I3riWDEN8Ev3NfHEUYk"; //"YOUR_API_SECRET"
	const url = "https://zoom-api-signature.herokuapp.com"; // YOUR_FETCH_URL_FOR_GET_SIGNATURE

	/** request body to get signature */
	const requestBody = {
	    apiKey: API_KEY,
	    apiSecret: API_SECRET,
	    meetingNumber:  "<%= @meeting_id %>", // "YOUR_HOST_MEETING_NUMBER"
	    role: parseInt("<%= @role %>"), // 1 for host; 0 for attendee,
	};

	/** meetconfig to join meeting */
	const meetConfig = {
	    meetingNumber:  "<%= @meeting_id %>", // "YOUR_HOST_MEETING_NUMBER"
	    userName: '<%= @userName %>',
	    passWord: '<%= @password %>',
	};
	document
    .getElementById("join_meeting")
    .addEventListener("click", function (e) {
        e.preventDefault();
        /**join meeting called when join button clicked */
        console.log('on Click');
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(requestBody)
        })
        .then(res => res.json())
        .then(data => {
            console.log('signature recieved', data);
            ZoomMtg.init({
                isSupportAV: true,
                leaveUrl: '<%= @root_url %>meetings/list_meetings',
                success: function () {
                    console.log('zoom init success');
                    ZoomMtg.join({
                        meetingNumber: meetConfig.meetingNumber,
                        userName: meetConfig.userName,
                        passWord: meetConfig.passWord,
                        signature: data.signature,
                        apiKey: API_KEY,
                        success: function (success) {
                            console.log('meeting joined success.');
                            $('[aria-label="open the chat pane"]').replaceWith('<button class=" footer-button__button ax-outline" data-target="ga_chat_modal" id="ga_chat_button" type="button" aria-label="close the chat pane" style="padding-left: 200px; background: rgb(66, 67, 69);"><div class="footer-button__img-layer"><div class="footer-button__chat-icon"></div></div><span class="footer-button__button-label">Chat</span></button>');
                            $('#ga_chat_button').click(function(){
                                console.log('custome ga_chat_button clicked success.');
                                $('#ga_chat_modal').addClass("is-active");
                            });
                            $('#ga_chat_close_button').click(function(){
                                $('#ga_chat_modal').removeClass("is-active");
                            });
                            // ga_chat_close_button
                            // $('[aria-label="open the chat pane"]').click(function(){
                            //     alert("chat clicked");
                            //     console.log("chat clicked   ");
                            // });
                        },
                        error: function (error) {
                            console.log('you have error in meeting join method',error);
                        }
                    })
                },
                error: function (error) {
                    console.log('Error in zoom  meeting init.',error)
                }
            });
        });
    });
</script>

app/views/users/delete_user.html.erb
<h1>Users#delete_user</h1>
<p>Find me in app/views/users/delete_user.html.erb</p>

app/views/users/get_user.html.erb
<h1>Users#get_user</h1>
<p>Find me in app/views/users/get_user.html.erb</p>

app/views/users/list_user.html.erb
<div class="column is-half ">  
  <% @users_data["users"].each do |user| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <% if user['pic_url'].nil? %>
              <img src="https://bulma.io/images/placeholders/64x64.png">
            <% else %>
              <img src="<%=user['pic_url']%>">
            <% end %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= user["first_name"] %> <%= user["last_name"] %></strong>
            <p><%= user["email"]%></p>
            <p><%= user["id"]%></p>
          </div>
        </div>
        
          <nav class="level">
            <div class="level-left is-mobile">
                <%#= link_to "Join meeting", room, class: "level-item" %>
                <%#= link_to edit_room_path(room), class: "level-item" do %>
                  <!-- <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span> -->
                <%# end %>
                <%= link_to user_delete_path(user["id"]), method: :delete, data: { confirm: 'Are you sure want to delete Room?' } do%>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
              
            </div>
          </nav>
        
      </article>
    </div>
  <% end %>
</div>
    

app/views/users/new_user.html.erb
<div class="column is-half ">
  <article class="media box">
    <div class="media-content">
    	<%= form_for :user, url: "create" do |form| %>
		  
        <div class="field">
          <%= form.label :email, class: "label" %>
          <div class="control">            
            <%= form.text_field :email, class: "input", placeholder: "Enter Email" %><br>            
          </div>
        </div>

        <div class="field">
          <%= form.label :first_name, class: "label" %>
          <div class="control">            
            <%= form.text_field :first_name, class: "input", placeholder: "Enter First Name" %><br>            
          </div>
        </div>

        <div class="field">
          <%= form.label :last_name, class: "label" %>
          <div class="control">            
            <%= form.text_field :last_name, class: "input", placeholder: "Enter Last Name" %><br>            
          </div>
        </div>

        <div class="field">
          <%= form.label :type, class: "label" %>
          <div class="control">
            <div class="select">
              <select id="user_type" name="user[type]" placeholder="Select User Type">
                <option value="1">Basic</option>
                <option value="2">Licensed</option>
                <option value="3">On-prem</option>
              </select>
            </div>
          </div>
        </div>

        
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit class: "button is-link" %>
          </div>
          <div class="control">
            <%#= link_to "Cancel", rooms_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </article>
</div>

app/views/users/update_user.html.erb
<h1>Users#update_user</h1>
<p>Find me in app/views/users/update_user.html.erb</p>